services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_portfolio_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-vite.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
